### ISSUE TITLE
第一次无法完整导入，第二次重复导入起报错。

### ISSUE THREAD

**Issue by YuukyuuKikan** [enximi/snowbreak_gacha_export#2]
Win10  无边框全屏  1600x900分辨率。国服简体中文，程序版本v0.21

尝试导入50%武器池。完整的抽卡记录一共有10页。
导入5页后提前停止，并且输出导入正常完成。
重复尝试导入时在第5页结束后报错退出，错误信息：

[2024-07-06T05:41:23Z ERROR snowbreak_gacha_export] failed to add records: merged_records_len: 90, index: 50, records: [OneRecord { star: 3, item_name: "伯班克的天空", item_type: Weapon, timestamp: 1718849520 }, OneRecord { star: 5, item_name: "海王星", item_type: Weapon, timestamp: 1718881740 }]

追加：
尝试删除全部记录全新导入，发现第一次导入提前停止发生的位置随机，但是之后重复导入一般会在第一次停止的位置弹错。
追加2：
分辨率1920x1080可以显著改善初次导入的成功率。

**Comment by enximi** [comment]
这个报错的意思是合并先前的记录和这一次导出的记录失败了，应该是两次运行中同一条记录的ocr识别的结果不一样。只在1920x1080和2560x1440简单测试过，1600x900可能ocr有问题。
等几天发布一个带有记录功能的版本，你再帮我运行看看问题出在哪里。另外，1920x1080的时候第一次导入页会失败吗，之后的导出合并会失败吗。

**Comment by YuukyuuKikan** [comment]
> 另外，1920x1080的时候第一次导入页会失败吗，之后的导出合并会失败吗。

感谢你的答复
我在自己的机器上反复测试了几次。
1920x1080的时候第一次导入也是会失败的，比1600x900的成功率会高但是并不是一定成功
在第一次导入成功之后，后续尝试导入合并也会失败，失败的位置随机，但是报错信息和上面的类似。

>[OneRecord { star: 3, item_name: "沉默的真相", item_type: Weapon, timestamp: 1718813460 }, OneRecord { star: 3, item_name: "铸铁卫士", item_type: Weapon, timestamp: 1718849460 }]

我注意到这两条记录出现在不同页面的同一个位置，有可能是识别的太急了导致第10页实际识别了第9页。

我提出一些猜想：1  适当延长每页停留时间（0.5s/页？）。2  相同的内容识别两次，彼此一致之后再写入，否则再次尝试识别。
应该1就能解决问题了。2可能适用于低分辨率的画面。

**Comment by YuukyuuKikan** [comment]
继续追加新bug。

初次运行报错：
[2024-08-17T13:50:01Z INFO  snowbreak_gacha_export] banner type: LimitedCharacter100Percent
[2024-08-17T13:50:10Z INFO  snowbreak_gacha_export] ocring...
thread 'main' panicked at src\record_image.rs:238:46:
called `Result::unwrap()` on an `Err` value: Failed to parse date time: ParseError(TooLong)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

一旦任意报错后，之后所有的运行尝试都会报另一个错误，同时程序外面有黄色边框无法消除。需要重启电脑。
[2024-08-17T13:54:04Z INFO  snowbreak_gacha_export] banner type: LimitedCharacter100Percent
thread 'main' panicked at src\action.rs:18:31:
called `Result::unwrap()` on an `Err` value: Simulate("not all input events were sent. they may have been blocked by UIPI")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
